spring:
  config:
    import: optional:classpath:application-secret.yml

  cloud:
    openfeign:
      okhttp:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/finsight
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#admin 시더에 들어갈 값들
admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PW}

mailgun:
  api:
    base-url: ${mailgun.api.base-url}
    domain: ${mailgun.api.domain}
    key:    ${mailgun.api.key}

jwt:
  secret: ${jwt.secret}

# 공통 프로퍼티
server:
  port: 8081

#배포시에는 배포 IP로 할당되도록 변경
app:
  base-url: http://localhost:${server.port}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
