spring:
  servlet:
    multipart:
      max-file-size: 10MB       # 원하는 최대 파일 크기
      max-request-size: 10MB
  config:
    import: optional:classpath:application-secret.yml

  cloud:
    openfeign:
      okhttp:
        enabled: true
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: finsight-social-project
        profile-folder: team-project/profiles


  datasource:
    url: jdbc:postgresql://localhost:5432/finsight
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  # 배포시에는 배포 IP로 할당되도록 변경
  base-url: http://localhost:${server.port}

#admin 시더에 들어갈 값들
admin:
  email: skygksmf5810@gmail.com
  password: asdfasdf123

mailgun:
  api:
    base-url: ${mailgun.api.base-url}
    domain: ${mailgun.api.domain}
    key:    ${mailgun.api.key}

jwt:
  secret: ${jwt.secret}

# 공통 프로퍼티
server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
