# src/main/resources/application.yml
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    openfeign:
      okhttp:
        enabled: true
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET}
        profile-folder: ${AWS_S3_PROFILE_FOLDER}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        jdbc:
          time_zone: ${SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE:UTC}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

app:
  base-url: "${APP_BASE_URL:http://52.79.38.106:8081}}"

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PW}

mailgun:
  api:
    base-url: ${MAILGUN_API_BASE_URL}
    domain: ${MAILGUN_DOMAIN}
    key: ${MAILGUN_API_KEY}

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8080

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:DEBUG}

#Swagger UI
springdoc:
  swagger-ui:
    urls:
      - name: Auth
        url: /api/auth/v3/api-docs
      - name: Portfolio
        url: /api/portfolio/v3/api-docs
      - name: Price
        url: /api/price/v3/api-docs
      - name: Order
        url: /api/order/v3/api-docs
      - name: Report
        url: /api/report/v3/api-docs
      - name: Tax
        url: /api/tax-report/v3/api-docs
      - name: SNS
        url: /api/sns/v3/api-docs

