version: '3.8'

services:
  db:
    image: postgres:15
    container_name: finsight-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: finsight
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - finsight-network

volumes:
  db-data:

networks:
  finsight-network:
    driver: bridge