version: '3.8'

services:
  ###############################################
  #  환경변수 파일 로드
  #  EC2에 배포할 때, GitHub Actions가
  #  .env.production 파일을 EC2로 복사해줌
  ###############################################
  db:
    image: postgres:15
    container_name: finsight-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - finsight-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: finsight-es
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - finsight-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: finsight-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - finsight-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: finsight-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - finsight-network

  redis:
    image: redis:7.2.4
    container_name: finsight-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - finsight-network

  ###############################################
  # 2) 애플리케이션 서비스 – ECR 에서 Pull
  ###############################################
  auth-service:
    image: "${ECR_REGISTRY_URL}/auth-service:${IMAGE_TAG}"
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - finsight-network

  portfolio-service:
    image: "${ECR_REGISTRY_URL}/portfolio-service:${IMAGE_TAG}"
    container_name: portfolio-service
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - finsight-network

  price-service:
    image: "${ECR_REGISTRY_URL}/price-service:${IMAGE_TAG}"
    container_name: price-service
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - finsight-network

  order-service:
    image: "${ECR_REGISTRY_URL}/order-service:${IMAGE_TAG}"
    container_name: order-service
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - db
      - kafka
    networks:
      - finsight-network

  report-service:
    image: "${ECR_REGISTRY_URL}/report-service:${IMAGE_TAG}"
    container_name: report-service
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - finsight-network

  tax-service:
    image: "${ECR_REGISTRY_URL}/tax-service:${IMAGE_TAG}"
    container_name: tax-service
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - finsight-network

  sns-service:
    image: "${ECR_REGISTRY_URL}/sns-service:${IMAGE_TAG}"
    container_name: sns-service
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
      - kafka
      - elasticsearch
    networks:
      - finsight-network

volumes:
  db-data:
  es-data:
  redis-data:

networks:
  finsight-network:
    driver: bridge
