version: '3.8'

services:
  # 데이터 저장소
  db:
    image: postgres:15
    container_name: finsight-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - finsight-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: finsight-es
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - finsight-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: finsight-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - finsight-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: finsight-kafka
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - finsight-network

  redis:
    image: redis:7.2.4
    container_name: finsight-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - finsight-network

  # 애플리케이션 서비스 (로컬 빌드)
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    image: auth-service:local
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - finsight-network

  portfolio-service:
    build:
      context: .
      dockerfile: portfolio-service/Dockerfile
    image: portfolio-service:local
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - finsight-network

  price-service:
    build:
      context: .
      dockerfile: price-service/Dockerfile
    image: price-service:local
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - finsight-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    image: order-service:local
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db
      - kafka
    networks:
      - finsight-network

  report-service:
    build:
      context: .
      dockerfile: report-service/Dockerfile
    image: report-service:local
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - finsight-network

  tax-service:
    build:
      context: .
      dockerfile: tax-service/Dockerfile
    image: tax-service:local
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - finsight-network

  sns-service:
    build:
      context: .
      dockerfile: sns-service/Dockerfile
    image: sns-service:local
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db
      - redis
      - kafka
      - elasticsearch
    networks:
      - finsight-network

  # 단일 진입점: Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: finsight-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - portfolio-service
      - price-service
      - order-service
      - report-service
      - tax-service
      - sns-service
    networks:
      - finsight-network

volumes:
  db-data:
  es-data:
  redis-data:

networks:
  finsight-network:
    driver: bridge
