spring:
  config:
    import: optional:classpath:application-secret.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/finsight
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 공통 프로퍼티
server:
  port: 8085

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
