# src/main/resources/application.yml
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

  websocket:
    allowed-origins: ${SPRING_WEBSOCKET_ALLOWED_ORIGINS:*}

  task:
    scheduling:
      pool:
        size: ${SPRING_TASK_SCHEDULING_POOL_SIZE:5}
      thread-name-prefix: ${SPRING_TASK_SCHEDULING_THREAD_NAME_PREFIX:sched-}
      timezone: ${SPRING_TASK_SCHEDULING_TIMEZONE:Asia/Seoul}

  cloud:
    openfeign:
      okhttp:
        enabled: true

    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET}
        profile-folder: ${AWS_S3_PROFILE_FOLDER}

app:
  base-url: "${APP_BASE_URL:http://localhost:${SERVER_PORT:8080}}"

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

finnhub:
  base-url: ${FINNHUB_BASE_URL:https://finnhub.io/api/v1}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:DEBUG}
