mailgun:
  api:
    base-url: https://api.mailgun.net/v3/sandbox29ba7e599607477b80676ecfcddfad23.mailgun.org
    domain: sandbox29ba7e599607477b80676ecfcddfad23.mailgun.org
    key: key-157ba35a8c691731e57aeccb93a24391-e71583bb-701c0d37

jwt:
  secret: U3VwZXJTZWNyZXRLZXlGb3JGSUFmZXI2MDEyMDAyMDIwMjQhISEhRXh0cmFMb25nU2VjcmV0S2V5Rm9yUzUxMkFsZ29yaXRobUV4dGVuZGVkVmVyc2lvbkZvckZpbnNpZ2h0U29jaWFsUHJvamVjdA==

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finsight
    username: finsight_user
    password: securepassword
    driver-class-name: org.postgresql.Driver