
  spring:
    application:
      name: tax-service

    profiles:
      active: ${SPRING_PROFILES_ACTIVE:prod}

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

    cloud:
      openfeign:
        okhttp:
          enabled: true

      aws:
        credentials:
          access-key: ${AWS_ACCESS_KEY_ID}
          secret-key: ${AWS_SECRET_ACCESS_KEY}
        region:
          static: ${AWS_REGION:ap-northeast-2}
        s3:
          bucket: ${AWS_S3_BUCKET}
          profile-folder: ${AWS_S3_PROFILE_FOLDER}

    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
      show-sql: ${SPRING_JPA_SHOW_SQL:true}
      properties:
        hibernate:
          jdbc:
            time_zone: ${SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE:UTC}
          format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
          dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

  app:
    base-url: "${APP_BASE_URL:http://localhost:${SERVER_PORT:8080}}"

  # 인증 서비스 URL
  auth:
    service:
      url: ${AUTH_SERVICE_URL}

  # 리포트 서비스 호출용 URL
  report:
    service:
      url: ${REPORT_SERVICE_URL}

  server:
    port: ${SERVER_PORT:8080}

  jwt:
    secret: ${JWT_SECRET}

  logging:
    level:
      root: ${LOGGING_LEVEL_ROOT:INFO}
      org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:DEBUG}

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha

  management:
    endpoints:
      web:
        exposure:
          include: health,info
        base-path: /actuator
    endpoint:
      health:
        show-details: when-authorized

