spring:
  config:
    import: optional:classpath:application-secret.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/finsight
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      okhttp:
        enabled: true

    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: finsight-post-images  #게시물 사진 업로드 버킷
        base-url: https://finsight-post-images.s3.ap-northeast-2.amazonaws.com

  elasticsearch:
    repositories:
      enabled: true
    client:
      reactive:
        endpoints: localhost:9200
    index:
      auto-create: true

app:
  # 배포시에는 배포 IP로 할당되도록 변경
  base-url: http://localhost:${server.port}

# 공통 프로퍼티
server:
  port: 8087

jwt:
  secret: ${jwt.secret}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
