spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true

    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION:ap-northeast-2}
      s3:
        # 게시물 사진 전용 S3 버킷
        bucket: ${POST_IMAGES_S3_BUCKET}
        # 해당 버킷의 공개 URL
        base-url: ${POST_IMAGES_S3_BASE_URL}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

  elasticsearch:
    repositories:
      enabled: ${ELASTICSEARCH_REPOSITORIES_ENABLED:true}
    client:
      reactive:
        endpoints: "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"
    index:
      auto-create: ${ELASTICSEARCH_INDEX_AUTO_CREATE:true}

app:
  base-url: "${APP_BASE_URL:http://localhost:${SERVER_PORT:8087}}"

server:
  port: ${SERVER_PORT:8087}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:DEBUG}
